services:
  web:
    container_name: furniture
    build: .
    # env_file:
    #   - .env.production
    ports:
      - "3077:3077"
    environment:
      - PORT=3077
      - TZ=Asia/Ho_Chi_Minh
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    dns:
      - 8.8.8.8
      - 1.1.1.1
